### ISSUE TITLE
Merge commands

### ISSUE THREAD

**Issue by regg00** [regg00/ChocoMan#1]
**Is your feature request related to a problem? Please describe.**
Not a problem. 
As stated here https://www.reddit.com/r/PowerShell/comments/15540ns/chocoman_a_powershell_wrapper_for_chocolaty/jsss27h/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1&context=3 some commands should be merged.

**Comment by BlackV** [comment]
Here is my Git as per reddit :)

**Comment by regg00** [comment]
`Get-ChocoPackages` should be removed and replacer with `Get-ChocoPackage`. By default, `Get-ChocoPackage` without the `-Name` parameter should return all installed packages.

`Get-ChocoOutdated` can stay there, but the `-Outdated` parameter shoud be added to `Get-ChocoPackage`.

Similarly, `Get-ChocoSources` should be renamed to `Get-ChocoSource` and should return all sources without the `-Name` parameter set.
