### ISSUE TITLE
Include Support for -Pre parameter

### ISSUE THREAD

**Issue by DailenG** [regg00/ChocoMan#28]
**Is your feature request related to a problem? Please describe.**
Rarely comes up but today I happened to need to get list of apps that had pre-releases available and realized there wasn't support for -Pre parameter.

**Describe the solution you'd like**
Support for passing off -Pre parameter specifically or perhaps an "overflow" parameter that will tag a string on the end of the choco command arguments so almost any parameter can be supported

I can add -Pre or an "Additional Arguments" overflow if you'd like to tell me your preference

**Comment by regg00** [comment]
I'm not a fan of the 'overflow' or `ValueFromRemainingArguments`.
I think it's cleaner to have a specific parameter for the required function instead of a "catchall" at the end.

So, yeah, I'd prefer a `-PreRelease` parameter.
