### ISSUE TITLE
Get Package Details

### ISSUE THREAD

**Issue by DailenG** [regg00/ChocoMan#31]
**Is your feature request related to a problem? Please describe.**
Not related to a problem per se, just an enhancement

**Describe the solution you'd like**
I'd like to be able to fetch details about a package. Mainly interested in tags (i.e. I might want to exclude showing admin utilities or prerequisite/runtimes by default, or only show packages applicable for a particular dept). This might not be a broadly used feature, but something I've needed several times. 

Line by line, the value output is inconsistent. Some lines contain multiple data/value pairs (i.e. Publish date is output on the same line as the package title). Aside from splitting out the data to a custom PS Object, the only other consideration I think is the fact that you can fetch details from locally installed packages AND repositories. I can see one of two solutions, adding -Details parameter to Search-ChocoPackage and Get-ChocoPackage or a standalone command Get-ChocoPackageDetails and specifying a parameter to designate where to get the details from.

**Describe alternatives you've considered**

**Additional context**
Attached sample output

![image](https://github.com/regg00/ChocoMan/assets/6981936/55159e72-006c-44cd-800c-4cf7bf4600d0)

**Comment by regg00** [comment]
Hey @DailenG.
I started to get working on this.
You can take a look at the dev branch attached to that issue.

I can't seem the reliably get the content of the description.
I only get the first line: 
![image](https://github.com/regg00/ChocoMan/assets/2913464/15658edd-3e40-4181-87d4-9ac454b38a19)

I guess my regex is the issue.
Do you have any insights to fix this? https://github.com/regg00/ChocoMan/blob/1ff52b7bed08b86e669628739618ff2a001ecd76/Public/Get/Get-ChocoPackage.ps1#L46

**Comment by DailenG** [comment]
Thanks for taking a look! I'll dive in tomorrow and see what I can make of it. 😎

**Comment by DailenG** [comment]
Submitted a PR. Not gonna lie I used ChatGPT to generate the basic functionality rather than screw with the regexp lol just made some adjustments and improvements to readability. Works good though 🙂

**Comment by regg00** [comment]
No shame in using ChatGPT. I use Copilot myself ;)

**Comment by DailenG** [comment]
So this may not be as ready as I thought it was, I switched it from using "choco info..." to invoke-chococommand and now it is being problematic 🤔

**Comment by regg00** [comment]
@DailenG I figured out how to properly parse the description field using the .NET `[regex]::matches`.
I'm closing this issue now.

**Comment by DailenG** [comment]
Nice work!
