### ISSUE TITLE
Enable piping of objects

### ISSUE THREAD

**Issue by we-mi** [regg00/ChocoMan#7]
First things first: This is module is great 👍 

I wanted to write my own powershell module for using choco, but I don't need that, because this is (almost, hence this issue) exactly how I want to use choco from within powershell.

**Is your feature request related to a problem? Please describe.**
Not really a problem. More like "using the full potential of powershell"-comfort-feature

**Describe the solution you'd like**

What you typically use pipelines for is something like this:

``` powershell
Get-Something | Filter-Something | Do-Something
```
What I want to use is something like that (I'll keep it simple, but you will get the point):

``` powershell
# I know that "Uninstall-ChocoPackage" is not implemented yet
Get-ChocoPackage | Where-Object { $_.Name -like "*vlc*" } | Uninstall-ChocoPackage
```

**Describe alternatives you've considered**

There is no alternative for the almighty powershell-pipeline :D  

OK, jokes aside. There's always another way (same result as example above):

``` powershell
Get-ChocoPackage | Where-Object { $_.Name -like "*vlc*" } | ForEach-Object { Uninstall-ChocoPackage -Name $_ }
```

or

``` powershell
$packages = Get-ChocoPackage | Where-Object { $_.Name -like "*vlc*" }
foreach($package in $packages) {
    Uninstall-ChocoPackage -Name $package
}
```

But i find the pipeline-approach of the cmdlets much more readable

**Additional context**
Please let me know if I can assist in any way by implementing this feature

**Comment by regg00** [comment]
Thanks @we-mi for the kind words.
It's always nice to know something you made is appreciated by someone.

I'll take a look at this feature request and let you know if I need help.
In the meantime, you can always fork it an create a PR if you want to.

**Comment by regg00** [comment]
Hey @we-mi, I just pushed a commit in the [branch](https://github.com/regg00/ChocoMan/tree/7-enable-piping-of-objects) linked to that issue.
Let me know what you think.

**Comment by we-mi** [comment]
Hey @regg00 ,

thanks for the update! I'll try this out as soon as i can, and get back in touch with you

**Comment by we-mi** [comment]
Hi @regg00 ,

i had some time looking at your implementation.

Although it is working, i want to point out some things.

Consider the following example:  
`Get-ChocoPackage "vlc" | Uninstall-ChocoPackage`

You are using `ValueFromPipeline` as a Parameter-Attribute for `$Name`, which only tries to map the pipeline inputs by the variable-types.
You specified no explicit type for $Name, so my guess is it defaults to `Object`, then you have one `Object`-Parameter which accepts pipeline input.

`Get-ChocoPackage -Name "vlc"` outputs an `PSCustomObject` (which can be converted to `Object`), in my case:

``` powershell
> $packages = Get-ChocoPackage -Name "vlc"
> $packages.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    PSCustomObject                           System.Object

> $packages

Name Version
---- -------
vlc  3.0.18
```

This output is piped to `Uninstall-ChocoPackage`, but the `$Name` parameter contains the whole object, instead of only the desired Package-Name, because it was automatically mapped due to the corresponding parameter-types.

Don't get me wrong. It works.
But imagine you have a cmdlet with two attributes which accept pipeline input. Lets say:

``` powershell
[Parameter(Mandatory = $true, Position = 0, ValueFromPipeline = $true)]
$Name,
[Parameter(Mandatory = $true, Position = 0, ValueFromPipeline = $true)]
$Version,
```

In the above example both `$Name` and `$Version` will contain the same object, if you use the pipeline-command from above. This works too, but is not the way it's intended to be.

Or if you specify the desired explicit type for the parameters:

``` powershell
[Parameter(Mandatory = $true, Position = 0, ValueFromPipeline = $true)]
[String]$Name,
[Parameter(Mandatory = $true, Position = 0, ValueFromPipeline = $true)]
[Version]$Version,
```

it would even lead to an error.  
The first `String`-Parameter contains the type-casted `Object`-Output from `Get-ChocoPackage` **as a string** (because `Object`-Variables can be converted to strings, but you can't access the attributes like with a normal `Object`).
The conversion from `Object` to `Version`-Type is not possible and therefore leads to an error.

Long story short: While this works, you have to workaround some things in order for it to work in the current implementation (what you did in lines 57 to 62 of `Uninstall-ChocoPackage.ps1`).

You can just use `ValueFromPipelineByPropertyName` instead of `ValueFromPipeline` and the parameter-mapping happens at the objects attribute-name level.

The input pipeline object for `Uninstall-ChocoPackage` does need an attribute `Name` in order to map it accordingly (which it does right now)
If you implement another parameter it needs to have this other name and so on.

With this you have more control how the parameters are mapped and you can just use them as defined in the `param`-block. If you pipe input to the cmdlet or not does not matter.

I'll create a PR with my changes :) The changes are marginal, that's why I wrote so much. I hope this clarified it a bit

**Comment by regg00** [comment]
@we-mi Thanks for the clarification and the PR.
I already tried the `ValueFromPipelineByPropertyName` way a couple of days ago, but I kept getting the same error:

 ```
PS ~> get-chocopackage -Name rufus | uninstall-package

Uninstall-Package: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.```

This error is from your PR #10.
I had the exact same error before, that's why used `ValueFromPipeline` with the workaround you mentioned.

Does it work on your end?

**Comment by regg00** [comment]
> @we-mi Thanks for the clarification and the PR. I already tried the `ValueFromPipelineByPropertyName` way a couple of days ago, but I kept getting the same error:
> 
> ```
> PS ~> get-chocopackage -Name rufus | uninstall-package
> 
> Uninstall-Package: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
> ```
> 
> This error is from your PR #10. I had the exact same error before, that's why used `ValueFromPipeline` with the workaround you mentioned. Does it work on your end?

Just forget everything I said above :disappointed_relieved:
I confused `Uninstall-Package` with ` Uninstall-ChocoPackage` the first time I tested `ValueFromPipelineByPropertyName`.

It works fine with the changes you requested:
``` powershell
PS C:\Users\regg0\GitHub\ChocoMan> get-chocopackage -Name rufus | Uninstall-ChocoPackage

Name  Status
----  ------
rufus Uninstalled
```

Again, thanks for the help on this.
It's really appreciated.
